services:
  backend:
    image: sugavanesh12/backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  frontend:
    image: sugavanesh12/drugi:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
